<?php

/**
 * CONFIG GLOBAL 
 */

//Chemin absolu de l'application :
define("RACINE", dirname(__DIR__));

//**CONSTANTES METIER
define("ADRESSE_METIER", RACINE . "/metier/Adresse.php");
define("AUTHENTIFICATION_METIER", RACINE . "/metier/Authentification.php");
define("CONSULTATION_METIER", RACINE . "/metier/Consultation.php");
define("IDENTITE_METIER", RACINE . "/metier/Identite.php");
define("INSCRIPTION_METIER", RACINE . "/metier/Inscription.php");
define("PATIENT_METIER", RACINE . "/metier/Patient.php");
define("PRATICIEN_METIER", RACINE . "/metier/Praticien.php");
define("RDV_METIER", RACINE . "/metier/Rdv.php");

//**CONSTANTES DAO
define("ADRESSE_DAO", RACINE . "/db/AdresseDAO.php");
define("CONNEXION", RACINE . "/db/Connexion.php");
define("CONSULTATION_DAO", RACINE . "/db/ConsultationDAO.php");
define("DAO", RACINE . "/db/DAO.php");
define("IDENTITE_DAO", RACINE . "/db/IdentiteDAO.php");
define("PATIENT_DAO", RACINE . "/db/PatientDAO.php");
define("PRATICIEN_DAO", RACINE . "/db/PraticienDAO.php");
define("RDV_DAO", RACINE . "/db/RdvDAO.php");

define('AUTHENTIFICATION', [CONNEXION, DAO, AUTHENTIFICATION_METIER, IDENTITE_METIER, IDENTITE_DAO]);
define('TESTC', [CONNEXION, DAO, IDENTITE_METIER, IDENTITE_DAO, ADRESSE_METIER, ADRESSE_DAO, PATIENT_METIER, PATIENT_DAO, PRATICIEN_METIER, PRATICIEN_DAO, CONSULTATION_METIER, CONSULTATION_DAO, RDV_METIER, RDV_DAO]);
define('CREATIONPATIENT', [CONNEXION, DAO, INSCRIPTION_METIER, AUTHENTIFICATION_METIER, ADRESSE_METIER, ADRESSE_DAO, IDENTITE_METIER, IDENTITE_DAO, PATIENT_METIER, PATIENT_DAO]);
define('DECONNEXION', [CONNEXION, DAO, AUTHENTIFICATION_METIER, IDENTITE_METIER, IDENTITE_DAO]);
define('FICHEPATIENT', [CONNEXION, DAO, AUTHENTIFICATION_METIER, ADRESSE_METIER, ADRESSE_DAO, IDENTITE_METIER, IDENTITE_DAO, PRATICIEN_METIER, PRATICIEN_DAO, CONSULTATION_METIER, CONSULTATION_DAO, RDV_METIER, RDV_DAO]);
define('INSCRIPTION', [CONNEXION, DAO, AUTHENTIFICATION_METIER, INSCRIPTION_METIER, ADRESSE_METIER, ADRESSE_DAO, IDENTITE_METIER, IDENTITE_DAO, PRATICIEN_METIER, PRATICIEN_DAO]);
define('RDV', [CONNEXION, DAO, AUTHENTIFICATION_METIER, ADRESSE_METIER, ADRESSE_DAO, IDENTITE_METIER, IDENTITE_DAO, PRATICIEN_METIER, PRATICIEN_DAO, PATIENT_METIER, PATIENT_DAO, CONSULTATION_METIER, CONSULTATION_DAO, RDV_METIER, RDV_DAO]);
define('RECHERCHE', [CONNEXION, DAO, AUTHENTIFICATION_METIER, ADRESSE_METIER, ADRESSE_DAO, IDENTITE_METIER, IDENTITE_DAO]);
define('PROFILPATIENT', [CONNEXION, DAO, AUTHENTIFICATION_METIER, ADRESSE_METIER, ADRESSE_DAO, IDENTITE_METIER, IDENTITE_DAO, PRATICIEN_METIER, PRATICIEN_DAO, PATIENT_METIER, PATIENT_DAO, CONSULTATION_METIER, CONSULTATION_DAO, RDV_METIER, RDV_DAO]);
